update "Origin" set system_id = (select id from "System" where system = 'Origin') WHERE id > 0;
update "Steam" set system_id = (select id from "System" where system = 'Steam') WHERE id > 0;
update "Ubisoft" set system_id = (select id from "System" where system = 'Ubisoft') WHERE id > 0;
update "GameCube" set system_id = (select id from "System" where system = 'GameCube') WHERE id > 0;
update "Wii" set system_id = (select id from "System" where system = 'Wii' And platform = 'Console') WHERE id > 0;
update "WiiU" set system_id = (select id from "System" where system = 'WiiU' And platform = 'Console') WHERE id > 0;

UPDATE "VirtualConsole" SET system_id = 10 WHERE id = 24;
UPDATE "VirtualConsole" SET system_id = 10 WHERE id = 25;
UPDATE "VirtualConsole" SET system_id = 9 WHERE id = 19;
UPDATE "VirtualConsole" SET system_id = 8 WHERE id = 14;
UPDATE "VirtualConsole" SET system_id = 11 WHERE id = 11;
UPDATE "VirtualConsole" SET system_id = 8 WHERE id = 12;
UPDATE "VirtualConsole" SET system_id = 8 WHERE id = 13;
UPDATE "VirtualConsole" SET system_id = 9 WHERE id = 18;
UPDATE "VirtualConsole" SET system_id = 14 WHERE id = 10;
UPDATE "VirtualConsole" SET system_id = 12 WHERE id = 4;
UPDATE "VirtualConsole" SET system_id = 12 WHERE id = 5;
UPDATE "VirtualConsole" SET system_id = 9 WHERE id = 20;
UPDATE "VirtualConsole" SET system_id = 15 WHERE id = 7;
UPDATE "VirtualConsole" SET system_id = 10 WHERE id = 26;
UPDATE "VirtualConsole" SET system_id = 15 WHERE id = 6;
UPDATE "VirtualConsole" SET system_id = 8 WHERE id = 16;
UPDATE "VirtualConsole" SET system_id = 10 WHERE id = 21;
UPDATE "VirtualConsole" SET system_id = 8 WHERE id = 17;
UPDATE "VirtualConsole" SET system_id = 8 WHERE id = 15;
UPDATE "VirtualConsole" SET system_id = 10 WHERE id = 22;
UPDATE "VirtualConsole" SET system_id = 10 WHERE id = 23;
UPDATE "VirtualConsole" SET system_id = 15 WHERE id = 3;
UPDATE "VirtualConsole" SET system_id = 15 WHERE id = 1;
UPDATE "VirtualConsole" SET system_id = 15 WHERE id = 2;
UPDATE "VirtualConsole" SET system_id = 12 WHERE id = 8;
UPDATE "VirtualConsole" SET system_id = 14 WHERE id = 9;