DROP TABLE IF EXISTS "Steam" CASCADE ;
DROP TABLE IF EXISTS "Origin" CASCADE ;
DROP TABLE IF EXISTS "Ubisoft" CASCADE ;

DROP TABLE IF EXISTS "GameCube" CASCADE ;
DROP TABLE IF EXISTS "Wii" CASCADE ;
DROP TABLE IF EXISTS "WiiU" CASCADE ;